tasks:
  - init: nvm install 14 && nvm use 14 && nvm alias default 14 && npm i
vscode:
  extensions:
    - standard.vscode-standard
    - atishay-jain.all-autocomplete
    - xabikos.javascriptsnippets
    - octref.vetur
    - digitalbrainstem.javascript-ejs-support
