import {
  faShoppingBag,
  faUser,
  faSignOutAlt,
  faSearch,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faArrowLeft,
  faArrowRight,
  faAngleRight,
  faTimes,
  faPhone,
  faEnvelope,
  faHistory,
  faBars,
  faShippingFast,
  faCreditCard,
  faExchangeAlt,
  faPercent,
  faHome,
  faTrashAlt,
  faCheck,
  faTruck,
  faLock,
  faShieldAlt
} from '@fortawesome/free-solid-svg-icons'

import {
  faFacebook,
  faFacebookF,
  faLinkedin,
  faGoogle,
  faWindows,
  faPinterest,
  faTwitter,
  faYoutube,
  faInstagram,
  faWhatsapp
} from '@fortawesome/free-brands-svg-icons'

import { library, dom } from '@fortawesome/fontawesome-svg-core'

library.add(
  faShoppingBag,
  faUser,
  faSignOutAlt,
  faSearch,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faArrowLeft,
  faArrowRight,
  faAngleRight,
  faTimes,
  faFacebook,
  faFacebookF,
  faLinkedin,
  faGoogle,
  faWindows,
  faPinterest,
  faTwitter,
  faYoutube,
  faInstagram,
  faWhatsapp,
  faPhone,
  faEnvelope,
  faHistory,
  faBars,
  faShippingFast,
  faCreditCard,
  faExchangeAlt,
  faPercent,
  faHome,
  faTrashAlt,
  faCheck,
  faTruck,
  faLock,
  faShieldAlt
)

dom.watch()
