import jQuery from './jquery/src/core.js'

import './jquery/src/selector.js'
import './jquery/src/traversing.js'
import './jquery/src/callbacks.js'
import './jquery/src/deferred.js'
import './jquery/src/deferred/exceptionHook.js'
import './jquery/src/core/ready.js'
import './jquery/src/data.js'
// import './jquery/src/queue.js'
// import './jquery/src/queue/delay.js'
import './jquery/src/attributes.js'
import './jquery/src/event.js'
import './jquery/src/event/alias.js'
import './jquery/src/event/trigger.js'
import './jquery/src/manipulation.js'
// import './jquery/src/manipulation/_evalUrl.js'
// import './jquery/src/wrap.js'
import './jquery/src/css.js'
import './jquery/src/css/showHide.js'
import './jquery/src/css/hiddenVisibleSelectors.js'
// import './jquery/src/serialize.js'
// import './jquery/src/ajax.js'
// import './jquery/src/ajax/xhr.js'
// import './jquery/src/ajax/script.js'
// import './jquery/src/ajax/jsonp.js'
import './jquery/src/core/parseHTML.js'
// import './jquery/src/ajax/load.js'
// import './jquery/src/event/ajax.js'
// import './jquery/src/effects.js'
// import './jquery/src/effects/animatedSelector.js'
import './jquery/src/offset.js'
import './jquery/src/dimensions.js'
// import './jquery/src/deprecated.js'
// import './jquery/src/exports/amd.js'
import './jquery/src/exports/global.js'

export default jQuery
